services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      # Minecraft version
      VERSION: "1.20.4"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "123"
      FTB_MODPACK_VERSION_ID: "12404"
      PVP: "false"
      MEMORY: "8G"
      OPS: |
        24a26761-efb2-4912-a38b-b81dd3f97959
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data