
services:
  minecraft-ftb:
    image: ghcr.io/tflashman/ftb:macm1
    container_name: minecraft-ftb
    restart: unless-stopped
    tty: true
    stdin_open: true
    stop_grace_period: 1m
    environment:
      - "FTB_MODPACK_ID=123"
      - "FTB_MODPACK_VERSION_ID=12404" #ftb neotech v. 1.7.0
      - "ACCEPT_MOJANG_EULA=1"
    volumes:
      - ./volume:/var/lib/minecraft:rw
    ports:
      - 25565:25565
    platform: linux/amd64